name: Publish NuGet Packages
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'  # Replace with the appropriate .NET Core version

      - name: Build and Pack NuGet packages
        run: |
          dotnet build --configuration Release
          dotnet pack --configuration Release

      - name: Publish NuGet packages
        uses: nuget/nuget-setapikey@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: Push NuGet packages
        run: |
          nuget_path=$(find . -name '*.nupkg' -print -quit)
          dotnet nuget push $nuget_path --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
